### ISSUE TITLE
Breaking changes to Wrapper derivation

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-amplify/amplify-derive#34]
- ~~Use IndexSlice instead of multiple Index implementations~~ IndexSlice does not work together with `Index<usize>`
- [x] rust-amplify/amplify-derive#33 
- [x] rust-amplify/amplify-derive#31
- [x] rust-amplify/amplify-derive#30 
- [x] rust-amplify/amplify-derive#29

**Comment by dr-orlovsky** [comment]
Closed by rust-amplify/rust-amplify#158
